### PR TITLE
Update security.rst

### PR DESCRIPTION
**Pull request by fabgg**
Add third argument on example of config of DefaultLoginRateLimiter.

After migrate 6.2 to 6.4.1 i got an error : 
Too few arguments to function Symfony\Component\Security\Http\RateLimiter\DefaultLoginRateLimiter::__construct(), 2 passed in /var/www/html/var/cache/dev/ContainerJcwPZ89/getSecurity_Listener_LoginThrottling_MainService.php on line 41 and exactly 3 expected

in the class

```php
/**
 * @param non-empty-string $secret A secret to use for hashing the IP address and username
 */
public function __construct(RateLimiterFactory $globalFactory, RateLimiterFactory $localFactory, #[\SensitiveParameter] string $secret)
{
    if (!$secret) {
        throw new InvalidArgumentException('A non-empty secret is required.');
    }

    $this->globalFactory = $globalFactory;
    $this->localFactory = $localFactory;
    $this->secret = $secret;
}
```

So,  it will be nice to update these config example section !

### CODE REVIEW

File: security.rst [hunk 1]
```diff
@@ -1601,6 +1601,7 @@ and set the ``limiter`` option to its service ID:
                     $globalFactory: '@limiter.ip_login'
                     # localFactory is the limiter for username+IP
                     $localFactory: '@limiter.username_ip_login'
+                    $secret: '%env(APP_SECRET)%'
```
Comment (wouterj) [inline security.rst]:
```suggestion
                    $secret: '%kernel.secret%'
```

File: security.rst [hunk 2]
```diff
@@ -1651,6 +1652,8 @@ and set the ``limiter`` option to its service ID:
                     <srv:argument type="service" id="limiter.ip_login"/>
                     <!-- 2nd argument is the limiter for username+IP -->
                     <srv:argument type="service" id="limiter.username_ip_login"/>
+                    <!-- 3rd argument is the app secret -->
+                    <srv:argument type="service" id="%env(APP_SECRET)%"/>
```
Comment (wouterj) [inline security.rst]:
```suggestion
                    <srv:argument type="service" id="%kernel.secret%"/>
```

**Review by wouterj — COMMENTED** [review]
You're correct, thanks for providing this fix!

Can you maybe also fix the PHP example (line 1698) by adding `'%kernel.secret%' to the list?

**Review by fabgg — COMMENTED** [review]
updated Rate limiter php config example

**Review by fabgg — COMMENTED** [review]
not confortable with github web pull request interface. Update php config example rate limiter

**Comment by OskarStark** [comment]
Thank you Fabrice.
